### ISSUE TITLE
Docker Container is not terminated after all repos are processed

### ISSUE THREAD

**Issue by albuch** [renovatebot/docker-renovate-full#326] opened 2021-03-18 17:01 UTC
Hi
we're seeing issues with the renovate Docker Container (self-hosted) not terminating in kubernetes after all discovered repositories are processed. We are having this issue since upgrading from v23.100.5 to v24.87.1+.

The last lines in the DEBUG log are
```
DEBUG: http statistics (repository=*****)
       "hostStats": [
         "api.github.com, 5 requests, 210ms request average, 0ms queue average",
         "auth.docker.io, 1 request, 280ms request average, 0ms queue average",
         "gitlab.com, 5 requests, 279ms request average, 0ms queue average",
         "index.docker.io, 5 requests, 263ms request average, 0ms queue average"
       ],
       "totalRequests": 16
INFO: Repository finished (repository=*****)
       "durationMs": 13383
DEBUG: Renovate exiting
```
However the container never terminates.

We're using image `renovate/renovate:24.89.1`
Any idea what might cause this issue?

**Comment by rarkins** [comment] 2021-03-18 17:31
Do any of your repositories connect to AWS ECR?

**Comment by albuch** [comment] 2021-03-18 17:58
Yes, we have many images in AWS ECR and that are updated in kubernetes manifest and gitlab CI files

**Comment by viceice** [comment] 2021-03-18 18:11
Try setting env `RENOVATE_X_HARD_EXIT=true`

https://docs.renovatebot.com/self-hosted-experimental/#renovate_x_hard_exit

**Comment by viceice** [comment] 2021-03-18 18:13
Duplicate of renovatebot/renovate#8660

**Closed** 2021-03-18 18:15 UTC
